name: linear-locks
version: 0.1.0.0
github: 'dcastro/linear-locks'
license: BSD-3-Clause
author: 'Diogo Castro'
maintainer: 'dc@diogocastro.com'
copyright: '2026 Diogo Castro'
category: Concurrency, Parallelism, Mutable State

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  `linear-locks` provides a `Mutex a` type that is statically guaranteed to not lead to deadlocks.
  Please see the README on GitHub at <https://github.com/dcastro/linear-locks#readme>

language: GHC2024

default-extensions:
  - BlockArguments
  - StrictData
  - TypeFamilies

ghc-options:
  - -Weverything
  - -Wno-name-shadowing
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-export-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-implicit-prelude
  - -Wno-prepositive-qualified-module
  - -Wno-missing-safe-haskell-mode
  - -Wno-missing-kind-signatures
  - -Wno-missing-role-annotations

library:
  source-dirs: src
  dependencies:
    - base >= 4.20
    - linear-base >= 0.4.0
    - stm-containers >= 1.2.1
    - focus >= 1.0.3.2
    - atomic-primops >= 0.8.4
    - vector >= 0.13.1.0
    - vector-algorithms >= 0.9.0.1
    - containers >= 0.6.8
    - deepseq >= 1.5.0.0
    - concurrent-extra >= 0.7.0.12

tests:
  linear-locks-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - linear-locks
      - linear-base
      - tasty
      - tasty-hunit-compat
      - hspec-expectations-pretty-diff
      - stm-containers
      - list-t
      - vector
      - concurrent-extra
    build-tools:
      - tasty-discover:tasty-discover
