name: linear-locks-examples
version: 0.1.0.0
github: 'dcastro/linear-locks'
license: BSD-3-Clause
author: 'Diogo Castro'
maintainer: 'dc@diogocastro.com'
copyright: '2026 Diogo Castro'

library:
  source-dirs: src
  dependencies:
    - base
    - linear-base
    - linear-locks
